name: hello-world
on: push
jobs:
  my-job:
    strategy:
      # Node versions list
      matrix:
        node-version: [20.x]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - run: make sayHello
