name: hello-world
on: push
jobs:
  my-job:
    strategy:
      # Node versions list
      matrix:
        node-version: [20.x]
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: sayHello
